### ISSUE TITLE
Get rid of the HTML elements

### ISSUE THREAD

**Issue by Lilkedus** [a-tanman/bible-vod#1]
Every time I get a verse, there's always HTML tags in that verse and it would be easier to read without the HTML tags

**Comment by a-tanman** [comment]
Thanks for flagging! Just to confirm the issue, is it only for <span> tags or have you seen other tags?

**Comment by a-tanman** [comment]
@Lilkedus, i've updated the extension and the issue with html tags should be resolved. thanks again!

**Comment by Lilkedus** [comment]
> @Lilkedus, i've updated the extension and the issue with html tags should be resolved. thanks again!



> Thanks for flagging! Just to confirm the issue, is it only for tags or have you seen other tags?

No, it's only for tags and HTML entities.
